baseurl = "https://markchristensen.dev/"
languageCode = "en-us"
pagination.pagerSize = 5

[module]
[[module.imports]]
  path = "github.com/panr/hugo-theme-terminal/v4"

[taxonomies]
  tag = "tags"

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = false
  showLanguageSelector = false
  themeColor = "green"

[languages]
  [languages.en]
    languageName = "English"
    title = "Tech Blog"

    [languages.en.params]
      subtitle       = "appsec // prodsec // devsecops // ai security"
      owner          = ""
      keywords       = "security, appsec, prodsec, devsecops, ai-security, blog"
      copyright      = ""
      menuMore       = "Show more"
      readMore       = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts     = "Newer posts"
      olderPosts     = "Older posts"
      missingContentMessage    = "Page not found..."
      missingBackButtonLabel   = "Back to home page"
      minuteReadingTime        = "min read"
      words                    = "words"

    [languages.en.params.logo]
      logoText     = "tech-blog $"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "blog"
      name       = "Blog"
      url        = "/posts"
      weight     = 1

    [[languages.en.menu.main]]
      identifier = "projects"
      name       = "Projects"
      url        = "/projects"
      weight     = 2

    [[languages.en.menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"
      weight     = 3
